# Generated by Django 5.2 on 2025-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('is_shown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
