# Generated by Django 5.2 on 2025-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('first_app.book',),
        ),
    ]
