# Generated by Django 5.2 on 2025-05-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_publishedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
