# Generated by Django 5.2 on 2025-05-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_blogpost_removed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('can_publish', 'can publish blog post'), ('can_archive', 'can archive blog post')]},
        ),
    ]
