# Generated by Django 5.2 on 2025-05-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'permissions': [('send_contact_us', 'can send contact us')]},
        ),
    ]
