
services:
  db:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.4.0-alpine
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --worker 3 maktab_django_126.wsgi:application
    - shared:/shared
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - shared:/shared
volumes:
  pgdata:
  shared: