
services:
  db:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    image: django_web:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: