# Generated by Django 5.2 on 2025-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_drf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(to='first_drf_app.employee'),
        ),
    ]
